apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurant-listing-default
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/codedecode25        
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds           
    argocd-image-updater.argoproj.io/git-branch: master                                          
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'git@github.com:udemy-dev-withK8s-AWS-codedecode/deployment-folder.git'
    path: ./aws
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true